module

public import RequestProject.MollifierEstimate

/-!
# Rellich compactness from a covering by shiftable pieces

Let `Ω ⊂ ℂ` be a bounded open set, covered by finitely many open sets `W_j ⊆ Ω` such that for
every `η > 0` each `W_j` admits a small closed ball `B̄(a_j, r_j)` (with `‖a_j‖ + r_j ≤ η`) of
admissible shifts: all segments `t - s z` with `t ∈ W_j`, `z ∈ B̄(a_j, r_j)`, `0 ≤ s ≤ 1` stay in
`Ω`. Then every sequence bounded in `H¹(Ω)` has an `L²(Ω)`-convergent subsequence.

The proof is the Kolmogorov–Riesz argument: on each piece `Q_j` of the partition generated by
the `W_j`, `u` is approximated within `η (‖g₀‖ + ‖g₁‖)` by the mollification `ρ_j ⋆ U` with a
bump `ρ_j` supported in `B̄(a_j, r_j)` (`l2norm_indicator_sub_mollify_le`); for fixed bumps the
mollifications of a bounded sequence are uniformly bounded and uniformly Lipschitz, hence lie in
a compact set of continuous functions (Arzelà–Ascoli).
-/

@[expose] public section

open MeasureTheory Filter Topology Metric Set

noncomputable section

namespace PolyaNeumann

/-- A compactness criterion: a sequence in a complete metric space that is, for every `ε > 0`,
within `ε` of some compact set, has a convergent subsequence. -/
theorem exists_tendsto_subseq_of_compact_approx {X : Type*} [MetricSpace X] [CompleteSpace X]
    (u : ℕ → X) (h : ∀ ε > 0, ∃ S : Set X, IsCompact S ∧ ∀ n, ∃ y ∈ S, dist (u n) y ≤ ε) :
    ∃ φ : ℕ → ℕ, StrictMono φ ∧ ∃ v, Tendsto (u ∘ φ) atTop (𝓝 v) := by
  have htb : TotallyBounded (range u) := by
    rw [Metric.totallyBounded_iff]
    intro ε hε
    obtain ⟨S, hS, hSu⟩ := h (ε / 3) (by positivity)
    obtain ⟨t, ht, htS⟩ := Metric.totallyBounded_iff.mp hS.totallyBounded (ε / 3) (by positivity)
    refine ⟨t, ht, ?_⟩
    rintro _ ⟨n, rfl⟩
    obtain ⟨y, hyS, hy⟩ := hSu n
    obtain ⟨z, hz, hyz⟩ := mem_iUnion₂.mp (htS hyS)
    refine mem_iUnion₂.mpr ⟨z, hz, ?_⟩
    rw [mem_ball] at hyz ⊢
    linarith [dist_triangle (u n) y z]
  have hc : IsCompact (closure (range u)) := htb.closure.isCompact_of_isClosed isClosed_closure
  obtain ⟨v, -, φ, hφ, hlim⟩ := hc.tendsto_subseq (x := u) fun n => subset_closure ⟨n, rfl⟩
  exact ⟨φ, hφ, v, hlim⟩

/-- The pieces `Q_j = W_j \ ⋃_{i<j} W_i` of the partition generated by a finite cover. -/
def partPiece {m : ℕ} (W : Fin m → Set ℂ) (j : Fin m) : Set ℂ :=
  W j \ ⋃ (i : Fin m) (_ : i < j), W i

lemma partPiece_subset {m : ℕ} (W : Fin m → Set ℂ) (j : Fin m) : partPiece W j ⊆ W j :=
  diff_subset

lemma measurableSet_partPiece {m : ℕ} {W : Fin m → Set ℂ} (hW : ∀ j, MeasurableSet (W j))
    (j : Fin m) : MeasurableSet (partPiece W j) :=
  (hW j).diff (MeasurableSet.iUnion fun i => MeasurableSet.iUnion fun _ => hW i)

lemma mem_partPiece_unique {m : ℕ} (W : Fin m → Set ℂ) {x : ℂ} {i j : Fin m}
    (hi : x ∈ partPiece W i) (hj : x ∈ partPiece W j) : i = j := by
  rcases lt_trichotomy i j with h | h | h
  · exact absurd (mem_iUnion₂.mpr ⟨i, h, hi.1⟩) hj.2
  · exact h
  · exact absurd (mem_iUnion₂.mpr ⟨j, h, hj.1⟩) hi.2

lemma exists_mem_partPiece {m : ℕ} (W : Fin m → Set ℂ) {x : ℂ} (hx : x ∈ ⋃ j, W j) :
    ∃ j, x ∈ partPiece W j := by
  classical
  have hne : (Finset.univ.filter fun j => x ∈ W j).Nonempty := by
    obtain ⟨j, hj⟩ := mem_iUnion.mp hx
    exact ⟨j, by simp [hj]⟩
  set j0 := (Finset.univ.filter fun j => x ∈ W j).min' hne
  have hj0 : x ∈ W j0 := by
    have := Finset.min'_mem _ hne
    simpa using this
  refine ⟨j0, hj0, ?_⟩
  simp only [mem_iUnion, not_exists]
  intro i hi hxi
  have : j0 ≤ i := Finset.min'_le _ i (by simp [hxi])
  exact absurd hi (not_lt.mpr this)

lemma sum_indicator_partPiece {m : ℕ} (W : Fin m → Set ℂ) (h : ℂ → ℂ) {x : ℂ}
    (hx : x ∈ ⋃ j, W j) : ∑ j, (partPiece W j).indicator h x = h x := by
  obtain ⟨j, hj⟩ := exists_mem_partPiece W hx
  rw [Finset.sum_eq_single j]
  · simp [hj]
  · intro i _ hij
    have : x ∉ partPiece W i := fun hi => hij (mem_partPiece_unique W hi hj)
    simp [this]
  · simp

lemma sum_indicator_partPiece_of_notMem {m : ℕ} (W : Fin m → Set ℂ) (h : Fin m → ℂ → ℂ)
    {x : ℂ} (hx : x ∉ ⋃ j, W j) : ∑ j, (partPiece W j).indicator (h j) x = 0 := by
  refine Finset.sum_eq_zero fun j _ => ?_
  have : x ∉ partPiece W j := fun hj => hx (mem_iUnion.mpr ⟨j, hj.1⟩)
  simp [this]

open Classical in
/-- Extension by zero of a bounded continuous function on `K ⊆ ℂ`. -/
def extBCF {K : Set ℂ} (f : BoundedContinuousFunction K ℂ) : ℂ → ℂ :=
  fun x => if h : x ∈ K then f ⟨x, h⟩ else 0

lemma norm_extBCF_le {K : Set ℂ} (f : BoundedContinuousFunction K ℂ) (x : ℂ) :
    ‖extBCF f x‖ ≤ ‖f‖ := by
  unfold extBCF
  split_ifs with h
  · exact f.norm_coe_le_norm _
  · simp

lemma extBCF_sub {K : Set ℂ} (f f' : BoundedContinuousFunction K ℂ) (x : ℂ) :
    extBCF f x - extBCF f' x = extBCF (f - f') x := by
  unfold extBCF
  split_ifs with h <;> simp

lemma aestronglyMeasurable_extBCF {K : Set ℂ} (hK : IsClosed K) {Ω : Set ℂ} (hΩK : Ω ⊆ K)
    (f : BoundedContinuousFunction K ℂ) :
    AEStronglyMeasurable (extBCF f) (volume.restrict Ω) := by
  have hc : ContinuousOn (extBCF f) K := by
    rw [continuousOn_iff_continuous_domRestrict]
    have : K.domRestrict (extBCF f) = f := by
      ext ⟨x, hx⟩; simp [Set.domRestrict_apply, extBCF, hx]
    rw [this]; exact f.continuous
  exact (hc.aestronglyMeasurable hK.measurableSet).mono_measure (Measure.restrict_mono hΩK le_rfl)

/-- The combination `∑_j 1_{Q_j} f_j` of bounded continuous functions as an element of
`L²(Ω)`. -/
lemma memLp_sum_piece {Ω K : Set ℂ} (hK : IsClosed K) (hΩK : Ω ⊆ K) (hΩ : volume Ω ≠ ⊤)
    {m : ℕ} {Q : Fin m → Set ℂ} (hQ : ∀ j, MeasurableSet (Q j))
    (f : Fin m → BoundedContinuousFunction K ℂ) :
    MemLp (fun x => ∑ j, (Q j).indicator (extBCF (f j)) x) 2 (volume.restrict Ω) := by
  haveI : IsFiniteMeasure (volume.restrict Ω) := isFiniteMeasure_restrict.mpr hΩ
  refine memLp_finset_sum _ fun j _ => ?_
  refine MemLp.of_bound ((aestronglyMeasurable_extBCF hK hΩK (f j)).indicator (hQ j)) ‖f j‖
    (Eventually.of_forall fun x => ?_)
  by_cases hx : x ∈ Q j
  · simp only [hx, indicator_of_mem]; exact norm_extBCF_le _ _
  · simp [hx]

/-- The map `(f_j)_j ↦ ∑_j 1_{Q_j} f_j` into `L²(Ω)`. -/
def pieceMap {Ω K : Set ℂ} (hK : IsClosed K) (hΩK : Ω ⊆ K) (hΩ : volume Ω ≠ ⊤)
    {m : ℕ} {Q : Fin m → Set ℂ} (hQ : ∀ j, MeasurableSet (Q j))
    (f : Fin m → BoundedContinuousFunction K ℂ) : L2 Ω :=
  (memLp_sum_piece hK hΩK hΩ hQ f).toLp _

lemma continuous_pieceMap {Ω K : Set ℂ} (hK : IsClosed K) (hΩK : Ω ⊆ K) (hΩ : volume Ω ≠ ⊤)
    {m : ℕ} {Q : Fin m → Set ℂ} (hQ : ∀ j, MeasurableSet (Q j)) :
    Continuous (pieceMap hK hΩK hΩ hQ) := by
  set κ : NNReal := ⟨(volume Ω).toReal ^ (1 / 2 : ℝ) * m, by positivity⟩
  refine (LipschitzWith.of_dist_le_mul (K := κ) fun f f' => ?_).continuous
  rw [dist_eq_norm, pieceMap, pieceMap, ← MemLp.toLp_sub, Lp.norm_toLp]
  have hb : ∀ x, ‖(fun x => ∑ j, (Q j).indicator (extBCF (f j)) x) x -
      (fun x => ∑ j, (Q j).indicator (extBCF (f' j)) x) x‖ ≤ m * dist f f' := by
    intro x
    simp only
    rw [← Finset.sum_sub_distrib]
    refine (norm_sum_le _ _).trans ?_
    have : ∀ j, ‖(Q j).indicator (extBCF (f j)) x - (Q j).indicator (extBCF (f' j)) x‖ ≤
        dist f f' := by
      intro j
      by_cases hx : x ∈ Q j
      · simp only [hx, indicator_of_mem, extBCF_sub]
        refine (norm_extBCF_le _ _).trans ?_
        rw [← dist_eq_norm]; exact dist_le_pi_dist f f' j
      · simp [hx, dist_nonneg]
    calc _ ≤ ∑ j : Fin m, dist f f' := Finset.sum_le_sum fun j _ => this j
      _ = m * dist f f' := by simp
  have := eLpNorm_le_of_ae_bound (μ := volume.restrict Ω) (p := 2)
    ((memLp_sum_piece hK hΩK hΩ hQ f).sub (memLp_sum_piece hK hΩK hΩ hQ f')).aestronglyMeasurable
    (Eventually.of_forall hb)
  rw [Measure.restrict_apply_univ] at this
  calc _ ≤ ((volume Ω) ^ (ENNReal.toReal 2)⁻¹ * ENNReal.ofReal (m * dist f f')).toReal :=
        ENNReal.toReal_mono (ENNReal.mul_ne_top (ENNReal.rpow_ne_top_of_nonneg (by norm_num) hΩ)
          ENNReal.ofReal_ne_top) this
    _ = κ * dist f f' := by
        rw [ENNReal.toReal_mul, ENNReal.toReal_ofReal (by positivity), ← ENNReal.toReal_rpow]
        rw [show (κ : ℝ) = (volume Ω).toReal ^ (1 / 2 : ℝ) * m from rfl]
        simp; ring

lemma mollify_eq_flip (ρ : ℂ → ℝ) (U : ℂ → ℂ) (x : ℂ) :
    mollify ρ U x = ∫ t, ρ (x - t) • U t := by
  rw [mollify, convolution_def]
  simp only [ContinuousLinearMap.lsmul_apply]
  rw [← integral_sub_left_eq_self (fun t => ρ t • U (x - t)) (μ := volume) x]
  simp

/-- Uniform bounds for mollifications: `|ρ ⋆ U| ≤ M ‖U‖₁` and `ρ ⋆ U` is `L ‖U‖₁`-Lipschitz. -/
lemma mollify_bounds {ρ : ℂ → ℝ} (hρ : ContDiff ℝ (⊤ : ℕ∞) ρ) (hρs : HasCompactSupport ρ) :
    ∃ M L : ℝ, 0 ≤ M ∧ 0 ≤ L ∧ ∀ U : ℂ → ℂ, Integrable U →
      (∀ x, ‖mollify ρ U x‖ ≤ M * ∫ t, ‖U t‖) ∧
      (∀ x y, ‖mollify ρ U x - mollify ρ U y‖ ≤ L * (∫ t, ‖U t‖) * ‖x - y‖) := by
  obtain ⟨M, hM⟩ := hρs.exists_bound_of_continuous hρ.continuous
  obtain ⟨L, hL⟩ := hρ.lipschitzWith_of_hasCompactSupport hρs (by simp)
  have hM0 : 0 ≤ M := (norm_nonneg _).trans (hM 0)
  refine ⟨M, L, hM0, L.2, fun U hU => ⟨fun x => ?_, fun x y => ?_⟩⟩
  · rw [mollify_eq_flip]
    calc ‖∫ t, ρ (x - t) • U t‖ ≤ ∫ t, M * ‖U t‖ := by
          refine norm_integral_le_of_norm_le (hU.norm.const_mul M)
            (Eventually.of_forall fun t => ?_)
          rw [norm_smul]; gcongr; exact hM _
      _ = M * ∫ t, ‖U t‖ := integral_const_mul _ _
  · rw [mollify_eq_flip, mollify_eq_flip]
    have hi : ∀ z, Integrable (fun t => ρ (z - t) • U t) := fun z =>
      (hU.norm.const_mul M).mono' ((hρ.continuous.comp (continuous_const.sub continuous_id)
        ).aestronglyMeasurable.smul hU.aestronglyMeasurable)
        (Eventually.of_forall fun t => by rw [norm_smul]; gcongr; exact hM _)
    rw [← integral_sub (hi x) (hi y)]
    calc ‖∫ t, (ρ (x - t) • U t - ρ (y - t) • U t)‖ ≤ ∫ t, (L * ‖x - y‖) * ‖U t‖ := by
          refine norm_integral_le_of_norm_le (hU.norm.const_mul _)
            (Eventually.of_forall fun t => ?_)
          rw [← sub_smul, norm_smul]
          gcongr
          have := hL.dist_le_mul (x - t) (y - t)
          simpa [dist_eq_norm] using this
      _ = L * (∫ t, ‖U t‖) * ‖x - y‖ := by rw [integral_const_mul]; ring

/-- `‖U‖₁ ≤ |Ω|^{1/2} ‖u‖` for the extension by zero. -/
lemma integral_norm_extZero_le {Ω : Set ℂ} (hΩ : MeasurableSet Ω) (hΩf : volume Ω ≠ ⊤)
    (u : L2 Ω) : Integrable (extZero Ω u) ∧
      ∫ t, ‖extZero Ω u t‖ ≤ (volume Ω).toReal ^ (1 / 2 : ℝ) * ‖u‖ := by
  haveI : IsFiniteMeasure (volume.restrict Ω) := isFiniteMeasure_restrict.mpr hΩf
  have hu1 : Integrable (fun x => u x) (volume.restrict Ω) := (Lp.memLp u).integrable one_le_two
  have hint : Integrable (extZero Ω u) := (integrable_indicator_iff hΩ).mpr hu1
  refine ⟨hint, ?_⟩
  have heq : ∫ t, ‖extZero Ω u t‖ = ∫ t in Ω, ‖u t‖ := by
    rw [← integral_indicator hΩ]
    congr 1; ext t; by_cases ht : t ∈ Ω <;> simp [extZero, ht]
  rw [heq]
  have h1 := eLpNorm_le_eLpNorm_mul_rpow_measure_univ (μ := volume.restrict Ω)
    (p := 1) (q := 2) (by norm_num) (Lp.memLp u).aestronglyMeasurable
  rw [Measure.restrict_apply_univ] at h1
  have h2 : eLpNorm (fun x => u x) 1 (volume.restrict Ω) = ENNReal.ofReal (∫ t in Ω, ‖u t‖) := by
    rw [(memLp_one_iff_integrable.mpr hu1).eLpNorm_eq_integral_rpow_norm (by norm_num)
      (by norm_num)]
    simp
  rw [h2] at h1
  have hnn : 0 ≤ ∫ t in Ω, ‖u t‖ := integral_nonneg fun _ => norm_nonneg _
  have := ENNReal.toReal_mono (ENNReal.mul_ne_top (Lp.memLp u).eLpNorm_ne_top
    (ENNReal.rpow_ne_top_of_nonneg (by norm_num) hΩf)) h1
  rw [ENNReal.toReal_ofReal hnn, ENNReal.toReal_mul, ← ENNReal.toReal_rpow] at this
  rw [Lp.norm_def]
  norm_num at this ⊢
  linarith

/-- **Arzelà–Ascoli** for uniformly bounded, uniformly Lipschitz sequences on a compact set. -/
lemma isCompact_closure_range_bcf {K : Set ℂ} [CompactSpace K] (F : ℕ → BoundedContinuousFunction K ℂ)
    (B L : ℝ) (hB : ∀ n x, ‖F n x‖ ≤ B) (hL : ∀ n x y, ‖F n x - F n y‖ ≤ L * dist x y) :
    IsCompact (closure (range F)) := by
  refine BoundedContinuousFunction.arzela_ascoli (closedBall 0 B) (isCompact_closedBall 0 B)
    (range F) ?_ ?_
  · rintro _ x ⟨n, rfl⟩
    simpa using hB n x
  · refine Metric.equicontinuous_of_continuity_modulus (fun d => L * d) ?_ _ ?_
    · simpa using (tendsto_id (x := 𝓝 (0:ℝ))).const_mul L
    · rintro x y ⟨_, n, rfl⟩
      rw [dist_eq_norm]; exact hL n x y

/-- **Rellich compactness from a cover by shiftable pieces.** -/
theorem rellich_of_cover {Ω : Set ℂ} (hΩ : IsOpen Ω) (hb : Bornology.IsBounded Ω) {m : ℕ}
    (W : Fin m → Set ℂ) (hWo : ∀ j, IsOpen (W j)) (hWΩ : ∀ j, W j ⊆ Ω)
    (hcov : Ω ⊆ ⋃ j, W j)
    (hshift : ∀ η > 0, ∀ j, ∃ a : ℂ, ∃ r > 0, ‖a‖ + r ≤ η ∧
      ∀ t ∈ W j, ∀ z ∈ closedBall a r, ∀ s ∈ Icc (0 : ℝ) 1, t - s • z ∈ Ω)
    (u : ℕ → L2 Ω) (g : ℕ → Fin 2 → L2 Ω) (hg : ∀ n, IsWeakGradient Ω (u n) (g n)) (C : ℝ)
    (hu : ∀ n, ‖u n‖ ≤ C) (hgC : ∀ n i, ‖g n i‖ ≤ C) :
    ∃ φ : ℕ → ℕ, StrictMono φ ∧ ∃ v : L2 Ω, Tendsto (u ∘ φ) atTop (𝓝 v) := by
  classical
  have hΩm := hΩ.measurableSet
  have hΩf : volume Ω ≠ ⊤ := hb.measure_lt_top.ne
  set K := closure Ω
  have hKc : IsCompact K := hb.isCompact_closure
  haveI : CompactSpace K := isCompact_iff_compactSpace.mp hKc
  have hKcl : IsClosed K := isClosed_closure
  have hΩK : Ω ⊆ K := subset_closure
  have hC0 : 0 ≤ C := (norm_nonneg _).trans (hu 0)
  set Q := partPiece W
  have hQm : ∀ j, MeasurableSet (Q j) := measurableSet_partPiece fun j => (hWo j).measurableSet
  refine exists_tendsto_subseq_of_compact_approx u fun ε hε => ?_
  set η := ε / ((m + 1) * (2 * C + 1))
  have hη : 0 < η := by positivity
  choose a r hr hηj hseg using hshift η hη
  let bump : ∀ j, ContDiffBump (a j) := fun j => ⟨r j / 2, r j, by linarith [hr j],
    by linarith [hr j]⟩
  set ρ : Fin m → ℂ → ℝ := fun j => (bump j).normed volume
  have hρd : ∀ j, ContDiff ℝ (⊤ : ℕ∞) (ρ j) := fun j => (bump j).contDiff_normed
  have hρs : ∀ j, HasCompactSupport (ρ j) := fun j => (bump j).hasCompactSupport_normed
  have hρt : ∀ j, tsupport (ρ j) = closedBall (a j) (r j) := fun j => (bump j).tsupport_normed_eq
  choose M L hM0 hL0 hML using fun j => mollify_bounds (hρd j) (hρs j)
  set U : ℕ → ℂ → ℂ := fun n => extZero Ω (u n)
  have hUi : ∀ n, Integrable (U n) := fun n => (integral_norm_extZero_le hΩm hΩf (u n)).1
  set I0 := (volume Ω).toReal ^ (1 / 2 : ℝ) * C
  have hUI : ∀ n, ∫ t, ‖U n t‖ ≤ I0 := fun n =>
    (integral_norm_extZero_le hΩm hΩf (u n)).2.trans
      (mul_le_mul_of_nonneg_left (hu n) (by positivity))
  have hmc : ∀ j n, Continuous (mollify (ρ j) (U n)) := fun j n =>
    (hρs j).continuous_convolution_left _ (hρd j).continuous (hUi n).locallyIntegrable
  let F : ℕ → Fin m → BoundedContinuousFunction K ℂ := fun n j =>
    BoundedContinuousFunction.mkOfCompact
      ⟨fun x => mollify (ρ j) (U n) x, (hmc j n).comp continuous_subtype_val⟩
  have hFa : ∀ n j (x : K), F n j x = mollify (ρ j) (U n) x := fun _ _ _ => rfl
  set A : Set (Fin m → BoundedContinuousFunction K ℂ) :=
    Set.pi univ (fun j => closure (range fun n => F n j))
  have hA : IsCompact A := by
    refine isCompact_univ_pi fun j => isCompact_closure_range_bcf _ (M j * I0) (L j * I0) ?_ ?_
    · intro n x
      rw [hFa]
      refine ((hML j (U n) (hUi n)).1 x).trans ?_
      exact mul_le_mul_of_nonneg_left (hUI n) (hM0 j)
    · intro n x y
      rw [hFa, hFa]
      refine ((hML j (U n) (hUi n)).2 x y).trans ?_
      rw [Subtype.dist_eq, dist_eq_norm]
      gcongr
      · exact hL0 j
      exact hUI n
  refine ⟨pieceMap hKcl hΩK hΩf hQm '' A, hA.image (continuous_pieceMap hKcl hΩK hΩf hQm),
    fun n => ⟨pieceMap hKcl hΩK hΩf hQm (F n), ⟨F n, fun j _ => subset_closure ⟨n, rfl⟩, rfl⟩, ?_⟩⟩
  -- the error on each piece
  set D : Fin m → ℂ → ℂ := fun j => (Q j).indicator (fun x => U n x - mollify (ρ j) (U n) x)
  have hest : ∀ j, eLpNorm (D j) 2 volume ≤ ENNReal.ofReal (η * (2 * C)) := by
    intro j
    have hR : ∀ z ∈ tsupport (ρ j), ‖z‖ ≤ η := by
      intro z hz
      rw [hρt j, mem_closedBall, dist_eq_norm] at hz
      have := norm_sub_norm_le z (a j)
      linarith [hηj j]
    obtain ⟨hmem, hle⟩ := l2norm_indicator_sub_mollify_le hΩ (hg n) (hWo j)
      (hb.subset (hWΩ j)) (hρd j).continuous (hρs j) (fun z => (bump j).nonneg_normed z)
      (bump j).integral_normed hη.le hR
      (fun t ht z hz s hs => hseg j t ht z (by rwa [hρt j] at hz) s hs)
    calc eLpNorm (D j) 2 volume ≤
          eLpNorm ((W j).indicator fun x => U n x - mollify (ρ j) (U n) x) 2 volume := by
          refine eLpNorm_mono (((hUi n).aestronglyMeasurable.sub
            (hmc j n).aestronglyMeasurable).indicator (hQm j)) fun x => ?_
          by_cases hx : x ∈ Q j
          · simp [D, hx, partPiece_subset W j hx]
          · simp [D, hx]
      _ = ENNReal.ofReal (l2norm ((W j).indicator fun x => U n x - mollify (ρ j) (U n) x)) :=
          (ENNReal.ofReal_toReal hmem.eLpNorm_ne_top).symm
      _ ≤ ENNReal.ofReal (η * (2 * C)) := by
          refine ENNReal.ofReal_le_ofReal (hle.trans ?_)
          gcongr
          linarith [hgC n 0, hgC n 1]
  -- the difference is the sum of the piecewise errors
  have hae : (fun x => (u n - pieceMap hKcl hΩK hΩf hQm (F n) : L2 Ω) x) =ᵐ[volume.restrict Ω]
      ∑ j, D j := by
    filter_upwards [Lp.coeFn_sub (u n) (pieceMap hKcl hΩK hΩf hQm (F n)),
      MemLp.coeFn_toLp (memLp_sum_piece hKcl hΩK hΩf hQm (F n)), ae_restrict_mem hΩm]
      with x h1 h2 hx
    rw [h1, Pi.sub_apply, pieceMap, h2, Finset.sum_apply]
    have hux : u n x = U n x := by simp [U, extZero, hx]
    have hext : ∀ j, extBCF (F n j) x = mollify (ρ j) (U n) x := fun j => by
      simp [extBCF, hΩK hx, hFa]
    rw [hux]
    conv_lhs => rw [← sum_indicator_partPiece W (U n) (hcov hx)]
    rw [← Finset.sum_sub_distrib]
    refine Finset.sum_congr rfl fun j _ => ?_
    by_cases hxq : x ∈ partPiece W j
    · simp [D, Q, hxq, hext j]
    · simp [D, Q, hxq]
  rw [dist_eq_norm, Lp.norm_def, eLpNorm_congr_ae hae]
  have hsum : eLpNorm (∑ j, D j) 2 (volume.restrict Ω) ≤ ENNReal.ofReal (m * (η * (2 * C))) := by
    calc eLpNorm (∑ j, D j) 2 (volume.restrict Ω) ≤ eLpNorm (∑ j, D j) 2 volume :=
          eLpNorm_mono_measure _ Measure.restrict_le_self
      _ ≤ ∑ j, eLpNorm (D j) 2 volume := by
          exact eLpNorm_sum_le (by norm_num)
      _ ≤ ∑ _j : Fin m, ENNReal.ofReal (η * (2 * C)) := Finset.sum_le_sum fun j _ => hest j
      _ = ENNReal.ofReal (m * (η * (2 * C))) := by
          rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul,
            ← ENNReal.ofReal_natCast, ← ENNReal.ofReal_mul (Nat.cast_nonneg _)]
  refine (ENNReal.toReal_mono ENNReal.ofReal_ne_top hsum).trans ?_
  rw [ENNReal.toReal_ofReal (by positivity)]
  have hm0 : (0 : ℝ) ≤ m := Nat.cast_nonneg m
  have : (m : ℝ) * (2 * C) ≤ (m + 1) * (2 * C + 1) := by nlinarith
  calc (m : ℝ) * (η * (2 * C)) = η * (m * (2 * C)) := by ring
    _ ≤ η * ((m + 1) * (2 * C + 1)) := by gcongr
    _ = ε := by
        simp only [η]
        field_simp

end PolyaNeumann

end
